import React from 'react';
import { BookOpen, Star, Users, Zap, Scroll, Globe } from 'lucide-react';
import { Category, Question } from './types';

export const CATEGORIES: Category[] = [
  { id: 'ulul_azmi', name: 'Ulul Azmi', icon: <Star className="w-6 h-6 text-yellow-400" />, color: 'bg-emerald-600' },
  { id: 'mukjizat', name: 'Mukjizat Nabi', icon: <Zap className="w-6 h-6 text-blue-400" />, color: 'bg-indigo-600' },
  { id: 'sirah', name: 'Sejarah Nabi Muhammad SAW', icon: <BookOpen className="w-6 h-6 text-green-300" />, color: 'bg-teal-700' },
  { id: 'sejarah_nabi_rasul', name: 'Sejarah Nabi & Rasul', icon: <Globe className="w-6 h-6 text-cyan-200" />, color: 'bg-cyan-700' },
  { id: 'keluarga', name: 'Keluarga & Sahabat', icon: <Users className="w-6 h-6 text-pink-300" />, color: 'bg-rose-600' },
  { id: 'fakta_quran', name: 'Fakta Al-Quran', icon: <Scroll className="w-6 h-6 text-amber-200" />, color: 'bg-slate-700' },
];

export const ALL_QUESTIONS: Record<string, Question[]> = {
  ulul_azmi: [
    { q: "Siapakah Nabi yang memiliki mukjizat tongkat membelah lautan?", a: "Nabi Musa AS" },
    { q: "Nabi yang tidak hangus ketika dibakar oleh Raja Namrud adalah?", a: "Nabi Ibrahim AS" },
    { q: "Nabi yang bisa menyembuhkan orang buta dan menghidupkan orang mati atas izin Allah?", a: "Nabi Isa AS" },
    { q: "Nabi Nuh AS dikenal dengan mukjizat membuat apa?", a: "Bahtera (Kapal Besar)" },
    { q: "Siapakah Nabi penutup para nabi (Khatamul Anbiya)?", a: "Nabi Muhammad SAW" },
    { q: "Berapa lama Nabi Nuh AS berdakwah menurut Al-Quran?", a: "950 Tahun" },
    { q: "Kitab yang diturunkan kepada Nabi Musa AS adalah?", a: "Taurat" },
    { q: "Kitab yang diturunkan kepada Nabi Isa AS adalah?", a: "Injil" },
    { q: "Julukan 'Khalilullah' (Kekasih Allah) diberikan kepada Nabi?", a: "Nabi Ibrahim AS" },
    { q: "Siapakah raja zalim yang menjadi musuh Nabi Musa AS?", a: "Fir'aun" },
    { q: "Berapa jumlah Nabi yang bergelar Ulul Azmi?", a: "5 Nabi" },
    { q: "Anak Nabi Nuh AS yang menolak naik kapal dan tenggelam adalah?", a: "Kan'an" },
    { q: "Nabi Ibrahim AS diperintah Allah untuk menyembelih putranya yang bernama?", a: "Nabi Ismail AS" },
    { q: "Siapakah saudara Nabi Musa AS yang menemaninya berdakwah?", a: "Nabi Harun AS" },
    { q: "Nabi Isa AS lahir dari seorang ibu suci bernama?", a: "Maryam" },
    { q: "Azab yang menimpa kaum Nabi Nuh AS adalah?", a: "Banjir Bandang Besar" },
    { q: "Nabi Isa AS akan turun kembali ke bumi menjelang kiamat untuk membunuh?", a: "Dajjal" },
    { q: "Gelar Ulul Azmi diberikan karena para Nabi tersebut memiliki?", a: "Kesabaran & Ketabahan Luar Biasa" },
    { q: "Nabi Ibrahim AS menghancurkan berhala-berhala menggunakan?", a: "Kapak" },
    { q: "Kaum Nabi Musa AS dikenal dengan sebutan Bani?", a: "Bani Israil" }
  ],
  mukjizat: [
    { q: "Nabi yang dapat berbicara dengan binatang dan jin adalah?", a: "Nabi Sulaiman AS" },
    { q: "Nabi yang mengeluarkan unta betina dari batu besar sebagai mukjizat?", a: "Nabi Saleh AS" },
    { q: "Nabi yang selamat setelah ditelan ikan paus adalah?", a: "Nabi Yunus AS" },
    { q: "Mukjizat Nabi Yusuf AS yang paling terkenal selain ketampanannya adalah?", a: "Menafsirkan Mimpi" },
    { q: "Nabi yang bisa melunakkan besi dengan tangannya adalah?", a: "Nabi Daud AS" },
    { q: "Air yang memancar dari sela-sela jari adalah mukjizat Nabi?", a: "Nabi Muhammad SAW" },
    { q: "Nabi yang diangkat ke langit dan belum wafat hingga kini adalah?", a: "Nabi Isa AS" },
    { q: "Angin yang bisa dikendalikan sebagai kendaraan adalah mukjizat Nabi?", a: "Nabi Sulaiman AS" },
    { q: "Peristiwa terbelahnya bulan adalah mukjizat Nabi?", a: "Nabi Muhammad SAW" },
    { q: "Nabi yang tongkatnya berubah menjadi ular besar adalah?", a: "Nabi Musa AS" },
    { q: "Nabi yang bisa menghidupkan burung dari tanah liat atas izin Allah?", a: "Nabi Isa AS" },
    { q: "Api menjadi dingin adalah mukjizat Nabi?", a: "Nabi Ibrahim AS" },
    { q: "Siapakah Nabi yang tangannya bisa memancarkan cahaya putih?", a: "Nabi Musa AS" },
    { q: "Sumur Zam-zam muncul dari hentakan kaki Nabi?", a: "Nabi Ismail AS (Kecil)" },
    { q: "Hidangan makanan turun dari langit (Al-Maidah) adalah mukjizat Nabi?", a: "Nabi Isa AS" },
    { q: "Baju gamisnya dapat menyembuhkan mata ayahnya yang buta adalah mukjizat Nabi?", a: "Nabi Yusuf AS" },
    { q: "Awan yang menaungi perjalanan adalah tanda kenabian?", a: "Nabi Muhammad SAW" },
    { q: "Nabi Zakariya diberi mukjizat berupa anak di usia sangat tua bernama?", a: "Nabi Yahya AS" },
    { q: "Siapakah Nabi yang mengerti bahasa semut?", a: "Nabi Sulaiman AS" },
    { q: "Al-Quran adalah mukjizat terbesar sepanjang masa milik Nabi?", a: "Nabi Muhammad SAW" }
  ],
  sirah: [
    { q: "Di kota manakah Nabi Muhammad SAW dilahirkan?", a: "Mekkah" },
    { q: "Tahun kelahiran Nabi Muhammad SAW disebut tahun?", a: "Tahun Gajah" },
    { q: "Wahyu pertama turun kepada Nabi Muhammad SAW di mana?", a: "Gua Hira" },
    { q: "Peristiwa perjalanan Nabi dari Masjidil Haram ke Masjidil Aqsa disebut?", a: "Isra Miraj" },
    { q: "Siapakah wanita pertama yang dinikahi Nabi Muhammad SAW?", a: "Khadijah binti Khuwailid" },
    { q: "Masjid pertama yang dibangun oleh Nabi Muhammad SAW adalah?", a: "Masjid Quba" },
    { q: "Perang besar pertama dalam Islam bernama perang?", a: "Perang Badar" },
    { q: "Di usia berapakah Nabi Muhammad SAW diangkat menjadi Rasul?", a: "40 Tahun" },
    { q: "Siapakah paman Nabi yang sangat memusuhi Islam (Abu Lahab/Abu Thalib)?", a: "Abu Lahab" },
    { q: "Apa nama gua tempat Nabi bersembunyi saat dikejar kaum Quraisy ketika Hijrah?", a: "Gua Tsur" },
    { q: "Gelar 'Al-Amin' yang diberikan kepada Nabi Muhammad SAW artinya?", a: "Orang yang Terpercaya" },
    { q: "Siapakah sahabat yang menggantikan tidur di kasur Nabi saat malam Hijrah?", a: "Ali bin Abi Thalib" },
    { q: "Peristiwa pembebasan kota Mekkah dikenal dengan istilah?", a: "Fathu Makkah" },
    { q: "Kendaraan bersayap yang ditunggangi Nabi saat Isra Miraj bernama?", a: "Buraq" },
    { q: "Perjanjian damai antara kaum Muslimin dan Quraisy disebut Perjanjian?", a: "Hudaibiyah" },
    { q: "Perang di mana paman Nabi, Hamzah bin Abdul Muthalib, gugur syahid?", a: "Perang Uhud" },
    { q: "Masjid kedua yang dibangun Nabi dan menjadi pusat pemerintahan di Madinah?", a: "Masjid Nabawi" },
    { q: "Pendeta Nasrani yang melihat tanda kenabian pada Muhammad kecil bernama?", a: "Buhaira" },
    { q: "Tanggal berapakah Nabi Muhammad SAW dilahirkan dalam kalender Hijriyah?", a: "12 Rabiul Awal" },
    { q: "Di kota manakah Nabi Muhammad SAW wafat dan dimakamkan?", a: "Madinah" }
  ],
  keluarga: [
    { q: "Siapakah nama ayah Nabi Muhammad SAW?", a: "Abdullah bin Abdul Muthalib" },
    { q: "Siapakah nama ibu Nabi Muhammad SAW?", a: "Aminah binti Wahb" },
    { q: "Siapakah sahabat yang menemani Nabi saat hijrah ke Madinah?", a: "Abu Bakar Ash-Shiddiq" },
    { q: "Siapakah sepupu sekaligus menantu Nabi Muhammad SAW?", a: "Ali bin Abi Thalib" },
    { q: "Siapakah istri Nabi yang merupakan putri dari Abu Bakar?", a: "Aisyah RA" },
    { q: "Siapakah nama anak Nabi Muhammad SAW yang menikah dengan Ali bin Abi Thalib?", a: "Fatimah Az-Zahra" },
    { q: "Siapakah sahabat yang dijuluki 'Singa Allah'?", a: "Hamzah bin Abdul Muthalib" },
    { q: "Siapakah muadzin pertama dalam Islam?", a: "Bilal bin Rabah" },
    { q: "Siapakah kakek yang mengasuh Nabi Muhammad SAW saat kecil?", a: "Abdul Muthalib" },
    { q: "Siapakah ibu susuan Nabi Muhammad SAW dari Bani Sa'ad?", a: "Halimah As-Sa'diyah" },
    { q: "Siapakah Khalifah kedua yang bergelar Al-Faruq?", a: "Umar bin Khattab" },
    { q: "Siapakah Khalifah ketiga yang menikahi dua putri Nabi?", a: "Utsman bin Affan" },
    { q: "Cucu kesayangan Nabi Muhammad SAW adalah?", a: "Hasan dan Husain" },
    { q: "Istri Nabi yang pertama kali wafat menyusul beliau adalah?", a: "Zainab binti Jahsy" },
    { q: "Putri Nabi yang wafat 6 bulan setelah Nabi wafat?", a: "Fatimah Az-Zahra" },
    { q: "Paman Nabi yang selalu melindunginya namun wafat belum memeluk Islam?", a: "Abu Thalib" },
    { q: "Anak laki-laki Nabi Muhammad SAW dari Mariyah Al-Qibtiyah bernama?", a: "Ibrahim" },
    { q: "Siapakah wanita yang menyusui Nabi sebelum Halimah As-Sa'diyah?", a: "Tsuwaibah" },
    { q: "Sahabat yang sangat kaya dan dermawan, dijamin masuk surga?", a: "Abdurrahman bin Auf" },
    { q: "Sekretaris Nabi yang bertugas mencatat wahyu adalah?", a: "Zaid bin Tsabit" }
  ],
  fakta_quran: [
    { q: "Surah apa yang pertama kali diturunkan?", a: "Al-Alaq (ayat 1-5)" },
    { q: "Surah terpanjang dalam Al-Quran adalah?", a: "Al-Baqarah" },
    { q: "Surah terpendek dalam Al-Quran adalah?", a: "Al-Kautsar" },
    { q: "Surah yang disebut sebagai 'Jantung Al-Quran' adalah?", a: "Yasin" },
    { q: "Berapa jumlah juz dalam Al-Quran?", a: "30 Juz" },
    { q: "Siapakah satu-satunya wanita yang namanya disebut dalam Al-Quran?", a: "Maryam" },
    { q: "Surah yang tidak diawali dengan Bismillah adalah?", a: "At-Taubah" },
    { q: "Ayat Kursi terdapat dalam surah apa?", a: "Al-Baqarah (Ayat 255)" },
    { q: "Wahyu terakhir turun pada saat peristiwa apa?", a: "Haji Wada'" },
    { q: "Berapa lama proses turunnya Al-Quran (kurang lebih)?", a: "23 Tahun (22 tahun 2 bulan 22 hari)" },
    { q: "Surah pembuka dalam Al-Quran disebut?", a: "Al-Fatihah" },
    { q: "Surah penutup (terakhir) dalam urutan mushaf Al-Quran adalah?", a: "An-Nas" },
    { q: "Malaikat yang bertugas menyampaikan wahyu adalah?", a: "Malaikat Jibril" },
    { q: "Berapa jumlah total surah dalam Al-Quran?", a: "114 Surah" },
    { q: "Surah yang menceritakan tentang pemuda yang tertidur di gua disebut?", a: "Al-Kahfi" },
    { q: "Surah yang menceritakan tentang pasukan gajah adalah?", a: "Al-Fil" },
    { q: "Ayat terpanjang dalam Al-Quran adalah ayat tentang utang piutang di Surah?", a: "Al-Baqarah (Ayat 282)" },
    { q: "Surah yang nilainya sebanding dengan sepertiga Al-Quran adalah?", a: "Al-Ikhlas" },
    { q: "Al-Quran diturunkan pada bulan mulia, yaitu bulan?", a: "Ramadhan" },
    { q: "Golongan surah yang turun di Mekkah disebut?", a: "Makkiyah" }
  ],
  sejarah_nabi_rasul: [
    { q: "Manusia pertama yang diciptakan Allah SWT sekaligus Nabi pertama adalah?", a: "Nabi Adam AS" },
    { q: "Nabi yang pertama kali diajarkan menjahit pakaian dan menulis adalah?", a: "Nabi Idris AS" },
    { q: "Kaum 'Ad yang dibinasakan dengan angin topan adalah umat Nabi?", a: "Nabi Hud AS" },
    { q: "Kaum Tsamud yang dibinasakan dengan suara menggelegar adalah umat Nabi?", a: "Nabi Saleh AS" },
    { q: "Nabi yang diutus kepada kaum Sodom yang memiliki perilaku menyimpang adalah?", a: "Nabi Luth AS" },
    { q: "Siapakah Nabi yang merupakan ayah dari Nabi Yusuf AS dan punya 12 anak?", a: "Nabi Yaqub AS" },
    { q: "Nabi yang pernah menjadi bendahara atau menteri di Mesir setelah dipenjara adalah?", a: "Nabi Yusuf AS" },
    { q: "Nabi Ayyub AS diuji oleh Allah dengan penyakit apa selama bertahun-tahun?", a: "Penyakit Kulit Parah" },
    { q: "Nabi yang berdakwah kepada penduduk Madyan yang suka curang dalam timbangan adalah?", a: "Nabi Syuaib AS" },
    { q: "Nabi Yunus AS diutus untuk berdakwah kepada penduduk kota?", a: "Ninawa (Nineveh)" },
    { q: "Raja Jalut yang bertubuh raksasa berhasil dikalahkan oleh Nabi?", a: "Nabi Daud AS" },
    { q: "Ratu Balqis dari negeri Saba' masuk Islam di masa kenabian siapa?", a: "Nabi Sulaiman AS" },
    { q: "Nabi yang diberi amanah menjaga Maryam binti Imran di Baitul Maqdis adalah?", a: "Nabi Zakariya AS" },
    { q: "Nabi yang mati syahid dibunuh raja zalim demi mempertahankan hukum Allah adalah?", a: "Nabi Yahya AS" },
    { q: "Nabi Ilyas AS berdakwah kepada kaum yang menyembah berhala bernama?", a: "Ba'al" },
    { q: "Saudara kandung Nabi Musa AS yang juga diangkat menjadi Nabi untuk membantunya adalah?", a: "Nabi Harun AS" },
    { q: "Nabi Ismail AS adalah putra Nabi Ibrahim dari istri yang bernama?", a: "Siti Hajar" },
    { q: "Nabi Zulkifli AS dikenal dengan sifat utamanya yaitu?", a: "Sabar & Menepati Janji" },
    { q: "Siapakah Nabi yang dijuluki 'Bapak Para Nabi' (Abul Anbiya)?", a: "Nabi Ibrahim AS" },
    { q: "Kitab Zabur adalah kitab suci yang diturunkan kepada Nabi?", a: "Nabi Daud AS" }
  ]
};